### ISSUE TITLE
Guess punctuation userscript doesn't work under Greasemonkey in Firefox

### ISSUE THREAD

**Issue by trolley** [kellnerd/musicbrainz-bookmarklets#12]
I'm using Firefox 92.0 with Greasemonkey and don't get the "Guess punctuation" button on edit pages. I've tried with Tampermonkey in Chrome and it works fine.

**Comment by trolley** [comment]
I tried Violentmonkey in Firefox instead and it works, so either you can close this or you can take a look into why it doesn't work with Greasemonkey if you care. Thanks.

**Comment by kellnerd** [comment]
I just tried it myself (using Firefox 92.0 and Greasemonkey 4.11) and indeed the buttons did not show up:

> Script error in [Greasemonkey script https://github.com/kellnerd/musicbrainz-bookmarklets/MusicBrainz: Guess Unicode punctuation; version 2021.8.27]:
> ReferenceError: $ is not defined

This means that the script does not find the jQuery library which is bundled with MB's code.
Dropping the jQuery dependency is already on my todo list, so this userscript might work with Greasemonkey in the future. Personally I am using Violentmonkey on Firefox since Greasemonkey 4 caused problems with some of my most used userscripts.

**Comment by kellnerd** [comment]
Should be fixed in version 2021.10.5
