### ISSUE TITLE
Wrong Unicode conversion for "dash within numbers" and "range of numbers"

### ISSUE THREAD

**Issue by vzell** [kellnerd/musicbrainz-bookmarklets#13]
I tried the following conversion in an annotation field with the "Guess Unicode Punctuation" script:

# Before conversion (all three lines use hyphen minus (U0012) from the standard keyboard)
Figure Dash (U2012)	Used as a dash within numbers (e.g. 555-1212).
En Dash     (U2013)	Indicates a range of numbers (e.g. 1989-90).
Hyphen 	    (U2010)     Joins words and syllables of a word (e.g. co-operate) and used within dates (e.g. 2022-01-01 or 2021-31)

# After conversion
Figure Dash (U2012)	Used as a dash within numbers (e.g. 555–1212).                                                                 actual result: U2013   expected result: U2012
En Dash     (U2013)	Indicates a range of numbers (e.g. 1989‐90).                                                                   actual result: U2010   expected result: U2013
Hyphen 	    (U2010)     Joins words and syllables of a word (e.g. co‐operate) and used within dates (e.g. 2022‐01‐01 or 2021‐31)       actual result: U2010

So according to https://wiki.musicbrainz.org/User:Jacobbrett/English_Punctuation_Guide the first two lines seem to be wrong after conversion. Is this a supported case by the script ?

**Comment by kellnerd** [comment]
Thanks for your tests, currently numbers other than **dates** are not really handled well by the simple RegEx replacement transformations that the script is doing (as you have noticed).

I had not put much thought into figure dashes since they are very rarely to be found in song and album titles. Also it is often impossible to tell **ranges** and **grouped digits** apart. Your examples perfectly show why even a more complex logic can't do these correctly in all cases: 555-1212 could also be a range (since 1212 is greater than 555) while 1989-90 was unlikely to be a range if 90 was not an abbreviated year. So I had decided to keep it simple and interpret all remaining hyphen-minus between digits as range specifiers (en dash) 😅

The only ways I see how the script does not return wrong results for grouped digits is to...
1. **ignore** all hyphen-minus between digits which are not valid dates. I would rather avoid this as ranges in titles are much more common.
2. add **special cases** for e.g. ISBNs and (some) phone numbers (if even possible). It is probably overkill to have dedicated additional rules for these rare things which then have to be run needlessly for all titles. Currently I am very happy that I have condensed most cases into just 11 rules, but I might consider this in the future if there is demand.

I could probably use figure dashes if there are three or more groups of digits, I will have a look.

So far I was at least able to make the script handle the **1989-90 case** correctly, previously it interpreted that one as a partial ISO 8601 date. Now it tries to validate the date before doing the replacement and leaves invalid dates for the other transformation rules, which leads to 1989-90 interpreted as range (see d0ff0142fc944ef181dcf2cf018f1c963570f2c1).

**Comment by kellnerd** [comment]
> I could probably use figure dashes if there are three or more groups of digits (then it is definitely not a range and dates have already been converted before), I will have a look.

Done in c8348ac5f61c71d698739138c90413fae9e59721, now it only interprets two groups of digits as range (correctly or mistakenly).

I have released these changes in version 2022.1.1.

**Comment by vzell** [comment]
cool thx ... and happy new year
